name: null

channels: 
    - defaults

dependencies:
    - jupyter=1.0.0
    - matplotlib=3.3.1
    - numpy=1.19.1
    - pandas=1.1.3
    - python=3.7.9
    - scikit-learn=0.23.2
    - seaborn=0.11.0
